### ISSUE TITLE
build fails on mac

### ISSUE THREAD

**Issue by guymguym** [vmolsa/webrtc-native#2]
I ran `node build.js` (with node 0.12.2), and it failed like this:

```
...

________ running '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/code/webrtc-native/third_party/webrtc'
Updating projects from gyp files...
Hook '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' took 12.79 secs
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
target_arch = x64
host_arch = x64
configuration = Release
SKIP_SYNC = false
Enable / Disable Sync: 
export SKIP_SYNC=1
export SKIP_SYNC=0

________ running '/usr/bin/python -c import os,sys;script = os.path.join("trunk","check_root_dir.py");_ = os.system("%s %s" % (sys.executable,script)) if os.path.exists(script) else 0' in '/code/webrtc-native/third_party/webrtc'

________ running '/usr/bin/python -u src/sync_chromium.py --target-revision a12e1e10c4a910a4f8aa20e3ea8b611846f19ed9' in '/code/webrtc-native/third_party/webrtc'
Chromium already up to date:  a12e1e10c4a910a4f8aa20e3ea8b611846f19ed9

________ running '/usr/bin/python src/setup_links.py' in '/code/webrtc-native/third_party/webrtc'

________ running '/usr/bin/python src/third_party/instrumented_libraries/scripts/download_binaries.py' in '/code/webrtc-native/third_party/webrtc'

________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --bucket chromium-webrtc-resources src/resources' in '/code/webrtc-native/third_party/webrtc'

________ running '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/code/webrtc-native/third_party/webrtc'
Updating projects from gyp files...
Hook '/usr/bin/python src/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' took 11.96 secs
Building WebRTC Node Module
Updating projects from gyp files...
gyp: build/config.gypi not found (cwd: /code/webrtc-native) while reading includes of webrtc.gyp
child_process.js:1389
    throw err;
          ^
Error: Command failed: python /code/webrtc-native/third_party/webrtc/src/webrtc/build/gyp_webrtc webrtc.gyp
    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at Object.<anonymous> (/code/webrtc-native/build.js:160:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

So I made another attempt with `echo "{}" > build/config.gypi` and then I get a different error:

```
target_arch = x64
host_arch = x64
configuration = Release
SKIP_SYNC = true
Enable / Disable Sync: 
export SKIP_SYNC=1
export SKIP_SYNC=0
Building WebRTC Node Module
Updating projects from gyp files...
ninja: Entering directory `/code/webrtc-native/third_party/webrtc/src/out/Release'
ninja: error: obj/../../../webrtc-native.ninja:162: expected '=', got identifier
dule_internal_impl.a libjingle_p2p.a libsrtp.a | $
                     ^ near here
child_process.js:1389
    throw err;
          ^
Error: Command failed: ninja -C /code/webrtc-native/third_party/webrtc/src/out/Release
    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at Object.<anonymous> (/code/webrtc-native/build.js:166:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by vmolsa** [comment]
Build it with node-gyp rebuild --debug

**Comment by guymguym** [comment]
I did:
```
npm install node-gyp
node-gyp rebuild --debug
```
and it finished the build without errors.
so is the issue about missing build instructions because I just tried `node build.js`...
would be best if `npm install` would just take care of whatever is needed...
