### ISSUE TITLE
Unable to instlal it on windows 10, 64bit

### ISSUE THREAD

**Issue by HusnainAshfaq** [vmolsa/webrtc-native#21]
Following error on console, whn i try to install it.

 at Error (native)
 at Object.fs.linkSync (fs.js:869:18)
 at init (D:\WebRTCServerAsClient\node_modules\webrtc-native\scripts\build.js:41:6)
 at Object.<anonymous> (D:\WebRTCServerAsClient\node_modules\webrtc-native\scripts\build.js:291:3)
 at Module._compile (module.js:460:26)
 at Object.Module._extensions..js (module.js:478:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Function.Module.runMain (module.js:501:10)
 at startup (node.js:129:16)

**Comment by vmolsa** [comment]
Hi, I updated the module is it working now?
