### ISSUE TITLE
Debian Jessie: Install with node 5.3.0 failing

### ISSUE THREAD

**Issue by ax3l** [vmolsa/webrtc-native#24]
I have the install via `npm install webrtc-native --save` failing on debian jessie (with all prereg installed and successful build with an older nodejs version):

- `node` v5.3.0 (from https://deb.nodesource.com/node_5.x)
- `npm` v3.3.12

```
[...]
5091 info lifecycle webrtc-native@1.2.2~install: Failed to exec install script
5092 verbose unlock done using /home/ax3l/.npm/_locks/staging-4fd396471c691efe.lock for /home/ax3l/node_modules/.staging
5093 silly rollbackFailedOptional Starting
5094 silly rollbackFailedOptional Finishing
5095 silly runTopLevelLifecycles Starting
5096 silly runTopLevelLifecycles Finishing
5097 silly install printInstalled
5098 warn ENOENT ENOENT: no such file or directory, open '/home/ax3l/package.json'
5099 warn EPACKAGEJSON webrtc-native No description
5100 warn EPACKAGEJSON webrtc-native No repository field.
5101 warn EPACKAGEJSON webrtc-native No README data
5102 warn EPACKAGEJSON webrtc-native No license field.
5103 verbose stack Error: webrtc-native@1.2.2 install: `node scripts/install.js`
5103 verbose stack Exit status 1
5103 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
5103 verbose stack     at emitTwo (events.js:87:13)
5103 verbose stack     at EventEmitter.emit (events.js:172:7)
5103 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5103 verbose stack     at emitTwo (events.js:87:13)
5103 verbose stack     at ChildProcess.emit (events.js:172:7)
5103 verbose stack     at maybeClose (internal/child_process.js:818:16)
5103 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
5104 verbose pkgid webrtc-native@1.2.2
5105 verbose cwd /home/ax3l
5106 error Linux 3.16.0-4-amd64
5107 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "webrtc-native" "--verbose" "--save"
5108 error node v5.3.0
5109 error npm  v3.3.12
5110 error code ELIFECYCLE
5111 error webrtc-native@1.2.2 install: `node scripts/install.js`
5111 error Exit status 1
5112 error Failed at the webrtc-native@1.2.2 install script 'node scripts/install.js'.
5112 error Make sure you have the latest version of node.js and npm installed.
5112 error If you do, this is most likely a problem with the webrtc-native package,
5112 error not with npm itself.
5112 error Tell the author that this fails on your system:
5112 error     node scripts/install.js
5112 error You can get their info via:
5112 error     npm owner ls webrtc-native
5112 error There is likely additional logging output above.
5113 verbose exit [ 1, true ]
```

Am I doing something wrong?

I tried it with an older nodejs version before but got install warnings (and runtime segfaults).

**Comment by ax3l** [comment]
ok just looks like https://github.com/kmalakoff/lifecycle does not support that node version (yet)
