### ISSUE TITLE
require webrtc-native module error

### ISSUE THREAD

**Issue by white87332** [vmolsa/webrtc-native#27]
Hi, I get some error messages when I require webrtc-native module
 
```
Error: Cannot find module './build/Release/webrtc.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/tidenet/Documents/workspace/peer-to-peer/node_modules/webrtc-native/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tidenet/Documents/workspace/peer-to-peer/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

My os is mac osx.
XCode version is 7.2.1.
Node version is 5.6.0.

Thank you.

**Comment by vmolsa** [comment]
Hi, You need to build webrtc-native from source.. But I'm soon updating webrtc-native to latest WebRTC version and building module for latest node version..
